version: '3.9'

services:
  webinterface:
    build: app
    container_name: revelations-app
    hostname: app
    ports:
      - "3000:3000"
    volumes:
      - ./app/build:/app
    env_file:
      - .env
    depends_on:
      - fluentd
      - middleware
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.app
    networks:
      - revelations-net

  middleware:
    build: middleware
    container_name: revelations-middleware
    hostname: api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=dbuser:dbpass@mongo:27017
    depends_on:
      - docker-api
      - dataset-api
      - mongo
      - fluentd
    volumes:
      - ./middleware:/api
      - ./data/files:/files
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.api
    networks:
      - revelations-net

  docker-api:
    build: docker-api
    container_name: docker-management-api
    hostname: docker-api
    depends_on:
      - fluentd
    volumes:
      - ./docker-api:/api
      - ./data/files:/files
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.docker
    networks:
      - revelations-net

  dataset-api:
    build: dataset-api
    container_name: revelations-dataset-api
    hostname: dataset-api
    env_file:
        - env/flask.env
    depends_on:
      - fluentd
    volumes:
      - ./dataset-api:/api
      - ./data/files/datasets:/files
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.dataset
    networks:
      - revelations-net

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: revelations-mongo-express
    ports:
      - "8081:8081"
    env_file:
        - env/mongo-express.env
    depends_on:
      - mongo
    networks:
      - revelations-net

  mongo:
    build: mongo
    container_name: revelations-mongo
    hostname: mongo
    env_file:
        - env/mongo.env
    volumes:
      - ./data/mongo:/data/db
    networks:
      - revelations-net

  postgres-oauth:
    image: postgres:14.2-alpine3.15
    container_name: postgres-oauth
    hostname: postgres-oauth
    volumes:
      - ./data/oauth:/var/lib/postgresql/data
    env_file:
      - .env.oauth
      - env/database.env

    networks:
      - revelations-net

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: oauth-server
    hostname: oauth
    env_file:
      - env/database.env
      - .env.oauth
    ports:
      - "8080:8080"
    depends_on:
      - postgres-oauth
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.auth
    networks:
      - revelations-net

  fluentd:
    build: logs
    container_name: revelations-fluentd
    hostname: fluentd
    volumes:
      - ./logs:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - mongo
    networks:
      - revelations-net

  docs:
    build: docs
    container_name: revelations-docs
    hostname: docs
    volumes:
      - ./docs:/app
    networks:
      - revelations-net

networks:
  revelations-net:
    name: revelations-net
