version: '3.9'

services:
  webinterface:
    build: app
    container_name: revelations-app
    hostname: app
    ports:
      - "3000:3000"
    volumes:
      - ./app/build:/app
    env_file:
      - .env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.app
    networks:
      - revelations-net

  middleware:
    build: middleware
    container_name: revelations-middleware
    hostname: api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=dbuser:dbpass@mongo:27017
    volumes:
      - ./middleware:/api
      - ./data/files:/files
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.api
    networks:
      - revelations-net

  docker-api:
    build: docker-api
    container_name: docker-management-api
    hostname: docker-api
    volumes:
      - ./docker-api:/api
      - ./data/files:/files
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.docker
    networks:
      - revelations-net

  dataset-api:
    build: dataset-api
    container_name: revelations-dataset-api
    hostname: dataset-api
    environment:
      FLASK_APP: api
      FLASK_HOST: 0.0.0.0
      FLASK_ENV: development
    volumes:
      - ./dataset-api:/api
      - ./data/files/datasets:/files
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.dataset
    networks:
      - revelations-net

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: revelations-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_OPTIONS_EDITORTHEME: "dracula"
      ME_CONFIG_MONDODB_URL: mongodb://dbuser:dbpass@mongo:27017
      ME_CONFIG_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    depends_on:
      - mongo
    networks:
      - revelations-net

  mongo:
    build: mongo
    container_name: revelations-mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: revelations
    volumes:
      - ./data/mongo:/data/db
    networks:
      - revelations-net

  postgres-oauth:
    image: postgres:14.2-alpine3.15
    container_name: postgres-oauth
    hostname: postgres-oauth
    volumes:
      - ./data/oauth:/var/lib/postgresql/data
    env_file:
      - .env.oauth
    networks:
      - revelations-net

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: oauth-server
    hostname: oauth
    env_file:
      - .env.oauth
    ports:
      - "8080:8080"
    depends_on:
      - postgres-oauth
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.auth
    networks:
      - revelations-net

  fluentd:
    build: logs
    container_name: revelations-fluentd
    hostname: fluentd
    volumes:
      - ./logs:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - mongo
    networks:
      - revelations-net

networks:
  revelations-net:
    name: revelations-net
