version: '3.9'

services:
  webinterface:
    build: app
    container_name: revelations-app
    hostname: app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    networks:
      - revelations-net

  middleware:
    build: middleware
    container_name: revelations-middleware
    hostname: api
    ports:
      - "5000:5000"
    volumes:
      - ./middleware:/api
      - ./data/files:/files
    networks:
      - revelations-net

  docker-api:
    build: docker-api
    container_name: docker-management-api
    hostname: docker-api
    volumes:
      - ./docker-api:/api
      - ./data/files:/files
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - revelations-net

  postgres-oauth:
    image: postgres:14.2-alpine3.15
    container_name: postgres-oauth
    hostname: postgres-oauth
    volumes:
      - ./data/oauth:/var/lib/postgresql/data
    env_file:
      - .env.oauth
    networks:
      - revelations-net

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: oauth-server
    hostname: oauth
    env_file:
      - .env.oauth
    ports:
      - "8080:8080"
    depends_on:
      - postgres-oauth
    networks:
      - revelations-net

networks:
  revelations-net:
    name: revelations-net
